In [72]:
import pandas as pd

df_jan = pd.read_csv("dados_brutos/pagamentos_jan2026.csv")

print(df_jan.head())
print(df_jan.info())

          codigo_pagamento codigo_pagamento_resumido data_emissao  \
0  158146264312025DR801755              2025DR801755   2025-12-31
1  158146264312025DR801888              2025DR801888   2025-12-31
2  158146264312025OB005334              2025OB005334   2025-12-31
3  158146264312025OB005589              2025OB005589   2025-12-31
4  158146264312025OB005711              2025OB005711   2025-12-31

  codigo_tipo_documento                      tipo_documento        tipo_ob  \
0                    DR  Documento de Arrecadação Municipal  Não se aplica
1                    DR  Documento de Arrecadação Municipal  Não se aplica
2                    OB                      Ordem Bancária          OBPIX
3                    OB                      Ordem Bancária          OBPIX
4                    OB                      Ordem Bancária          OBPIX

  extraorcamentario  codigo_orgao_superior          orgao_superior  \
0               NÃO                  26000  Ministério da Educação
1               NÃO                  26000  Ministério da Educação
2               NÃO                  26000  Ministério da Educação
3               NÃO                  26000  Ministério da Educação
4               NÃO                  26000  Ministério da Educação

   codigo_orgao  ... codigo_programa_governo  nome_programa_governo  \
0         26431  ...                       0         Sem informação
1         26431  ...                       0         Sem informação
2         26431  ...                       0         Sem informação
3         26431  ...                       0         Sem informação
4         26431  ...                       0         Sem informação

  valor_original_pagamento  valor_pagamento_convertido_rs  \
0                     5,00                           5,00
1                     5,00                           5,00
2                   143,46                         143,46
3                   143,46                         143,46
4                   143,46                         143,46

  valor_utilizado_conversao mes_referencia        data_extracao  \
0                    1,0000     2025-12-01  2026-01-20 21:02:10
1                    1,0000     2025-12-01  2026-01-20 21:02:10
2                    1,0000     2025-12-01  2026-01-20 21:02:10
3                    1,0000     2025-12-01  2026-01-20 21:02:10
4                    1,0000     2025-12-01  2026-01-20 21:02:10

                                          url_origem  \
0  https://portaldatransparencia.gov.br/download-...
1  https://portaldatransparencia.gov.br/download-...
2  https://portaldatransparencia.gov.br/download-...
3  https://portaldatransparencia.gov.br/download-...
4  https://portaldatransparencia.gov.br/download-...

                         hash_dados  data_atualizacao_registro
0  a757cceed5e6f9f1dfacf634a8e9ce87        2026-01-20 18:03:32
1  c70666da733497a111c832a85b04cc36        2026-01-20 18:03:32
2  7c31cb7fff822dd894b7519c9db4c52c        2026-01-20 18:03:32
3  009cfb44cc4770b27b35322a6b647b02        2026-01-20 18:03:32
4  ee8004648b6a09c2c6e656a2f0d03a70        2026-01-20 18:03:32

[5 rows x 39 columns]
<class 'pandas.DataFrame'>
RangeIndex: 7597 entries, 0 to 7596
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   codigo_pagamento               7597 non-null   str
 1   codigo_pagamento_resumido      7597 non-null   str
 2   data_emissao                   7597 non-null   str
 3   codigo_tipo_documento          7597 non-null   str
 4   tipo_documento                 7597 non-null   str
 5   tipo_ob                        7597 non-null   str
 6   extraorcamentario              7597 non-null   str
 7   codigo_orgao_superior          7597 non-null   int64
 8   orgao_superior                 7597 non-null   str
 9   codigo_orgao                   7597 non-null   int64
 10  orgao                          7597 non-null   str
 11  codigo_unidade_gestora         7597 non-null   int64
 12  unidade_gestora                7597 non-null   str
 13  codigo_gestao                  7597 non-null   int64
 14  gestao                         7597 non-null   str
 15  codigo_favorecido              7597 non-null   str
 16  favorecido                     7597 non-null   str
 17  observacao                     7597 non-null   str
 18  processo                       6540 non-null   str
 19  codigo_categoria_despesa       7597 non-null   int64
 20  categoria_despesa              7597 non-null   str
 21  codigo_grupo_despesa           7597 non-null   str
 22  grupo_despesa                  7597 non-null   str
 23  codigo_modalidade_aplicacao    7597 non-null   str
 24  modalidade_aplicacao           7597 non-null   str
 25  codigo_elemento_despesa        7597 non-null   str
 26  elemento_despesa               7597 non-null   str
 27  codigo_plano_orcamentario      7597 non-null   int64
 28  plano_orcamentario             7597 non-null   str
 29  codigo_programa_governo        7597 non-null   str
 30  nome_programa_governo          7597 non-null   str
 31  valor_original_pagamento       7597 non-null   str
 32  valor_pagamento_convertido_rs  7597 non-null   str
 33  valor_utilizado_conversao      7597 non-null   str
 34  mes_referencia                 7597 non-null   str
 35  data_extracao                  7597 non-null   str
 36  url_origem                     7597 non-null   str
 37  hash_dados                     7597 non-null   str
 38  data_atualizacao_registro      7597 non-null   str
dtypes: int64(6), str(33)
memory usage: 2.3 MB
None

In [73]:
df_jan.head(3).T

,0,1,2
codigo_pagamento,158146264312025DR801755,158146264312025DR801888,158146264312025OB005334
codigo_pagamento_resumido,2025DR801755,2025DR801888,2025OB005334
data_emissao,2025-12-31,2025-12-31,2025-12-31
codigo_tipo_documento,DR,DR,OB
tipo_documento,Documento de Arrecadação Municipal,Documento de Arrecadação Municipal,Ordem Bancária
tipo_ob,Não se aplica,Não se aplica,OBPIX
extraorcamentario,NÃO,NÃO,NÃO
codigo_orgao_superior,26000,26000,26000
orgao_superior,Ministério da Educação,Ministério da Educação,Ministério da Educação
codigo_orgao,26431,26431,26431
orgao,"Instituto Federal de Educação, Ciência e T","Instituto Federal de Educação, Ciência e T","Instituto Federal de Educação, Ciência e T"
codigo_unidade_gestora,158146,158146,158146
unidade_gestora,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI"
codigo_gestao,26431,26431,26431
gestao,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI"
codigo_favorecido,***.256.903-**,***.320.168-**,***.271.213-**
favorecido,JOSELINA GOMES LIMA,DOMINGOS DA SILVA SOUSA,EDENIA RODRIGUES DE SOUSA
observacao,RETENCAO DE ISS REF. PRESTACAO DE SERVICO DE C...,RETENCAO DE ISS REF. PRESTACAO DE SERVICO DE C...,PAGAMENTO AOS COLABORADORES EXTERNOS QUE EXERC...
processo,NaN,NaN,23187.001586/2025-51
codigo_categoria_despesa,3,3,3
categoria_despesa,DESPESAS CORRENTES,DESPESAS CORRENTES,DESPESAS CORRENTES
codigo_grupo_despesa,3,3,3
grupo_despesa,Outras Despesas Correntes,Outras Despesas Correntes,Outras Despesas Correntes
codigo_modalidade_aplicacao,90,90,90
modalidade_aplicacao,Aplicações Diretas,Aplicações Diretas,Aplicações Diretas
codigo_elemento_despesa,36,36,36
elemento_despesa,Outros Serviços de Terceiros - Pessoa Físic,Outros Serviços de Terceiros - Pessoa Físic,Outros Serviços de Terceiros - Pessoa Físic
codigo_plano_orcamentario,0,0,0
plano_orcamentario,FUNCIONAMENTO DAS INSTITUICOES DA REDE FEDERAL...,FUNCIONAMENTO DAS INSTITUICOES DA REDE FEDERAL...,FUNCIONAMENTO DAS INSTITUICOES DA REDE FEDERAL...
codigo_programa_governo,0,0,0
nome_programa_governo,Sem informação,Sem informação,Sem informação
valor_original_pagamento,"5,00","5,00","143,46"
valor_pagamento_convertido_rs,"5,00","5,00","143,46"
valor_utilizado_conversao,"1,0000","1,0000","1,0000"
mes_referencia,2025-12-01,2025-12-01,2025-12-01
data_extracao,2026-01-20 21:02:10,2026-01-20 21:02:10,2026-01-20 21:02:10
url_origem,https://portaldatransparencia.gov.br/download-...,https://portaldatransparencia.gov.br/download-...,https://portaldatransparencia.gov.br/download-...
hash_dados,a757cceed5e6f9f1dfacf634a8e9ce87,c70666da733497a111c832a85b04cc36,7c31cb7fff822dd894b7519c9db4c52c
data_atualizacao_registro,2026-01-20 18:03:32,2026-01-20 18:03:32,2026-01-20 18:03:32

In [74]:
df_jan.shape

(7597, 39)

In [75]:
df_jan.info()

<class 'pandas.DataFrame'>
RangeIndex: 7597 entries, 0 to 7596
Data columns (total 39 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   codigo_pagamento               7597 non-null   str
 1   codigo_pagamento_resumido      7597 non-null   str
 2   data_emissao                   7597 non-null   str
 3   codigo_tipo_documento          7597 non-null   str
 4   tipo_documento                 7597 non-null   str
 5   tipo_ob                        7597 non-null   str
 6   extraorcamentario              7597 non-null   str
 7   codigo_orgao_superior          7597 non-null   int64
 8   orgao_superior                 7597 non-null   str
 9   codigo_orgao                   7597 non-null   int64
 10  orgao                          7597 non-null   str
 11  codigo_unidade_gestora         7597 non-null   int64
 12  unidade_gestora                7597 non-null   str
 13  codigo_gestao                  7597 non-null   int64
 14  gestao                         7597 non-null   str
 15  codigo_favorecido              7597 non-null   str
 16  favorecido                     7597 non-null   str
 17  observacao                     7597 non-null   str
 18  processo                       6540 non-null   str
 19  codigo_categoria_despesa       7597 non-null   int64
 20  categoria_despesa              7597 non-null   str
 21  codigo_grupo_despesa           7597 non-null   str
 22  grupo_despesa                  7597 non-null   str
 23  codigo_modalidade_aplicacao    7597 non-null   str
 24  modalidade_aplicacao           7597 non-null   str
 25  codigo_elemento_despesa        7597 non-null   str
 26  elemento_despesa               7597 non-null   str
 27  codigo_plano_orcamentario      7597 non-null   int64
 28  plano_orcamentario             7597 non-null   str
 29  codigo_programa_governo        7597 non-null   str
 30  nome_programa_governo          7597 non-null   str
 31  valor_original_pagamento       7597 non-null   str
 32  valor_pagamento_convertido_rs  7597 non-null   str
 33  valor_utilizado_conversao      7597 non-null   str
 34  mes_referencia                 7597 non-null   str
 35  data_extracao                  7597 non-null   str
 36  url_origem                     7597 non-null   str
 37  hash_dados                     7597 non-null   str
 38  data_atualizacao_registro      7597 non-null   str
dtypes: int64(6), str(33)
memory usage: 2.3 MB

In [76]:
df_jan.isnull().sum().sort_values(ascending=False).head(20)

processo                     1057
codigo_pagamento_resumido       0
codigo_pagamento                0
codigo_tipo_documento           0
tipo_documento                  0
tipo_ob                         0
data_emissao                    0
extraorcamentario               0
codigo_orgao_superior           0
codigo_orgao                    0
orgao_superior                  0
codigo_unidade_gestora          0
unidade_gestora                 0
codigo_gestao                   0
orgao                           0
gestao                          0
codigo_favorecido               0
favorecido                      0
observacao                      0
codigo_categoria_despesa        0
dtype: int64

In [77]:
arquivos = {
    "jan2026": "dados_brutos/pagamentos_jan2026.csv",
    "fev2026": "dados_brutos/pagamentos_fev2026.csv",
    "abr2026": "dados_brutos/pagamentos_abr2026.csv",
    "mai2026": "dados_brutos/pagamentos_mai2026.csv"
}

for mes, caminho in arquivos.items():
    df_temp = pd.read_csv(caminho)
    print(mes, df_temp.shape)

jan2026 (7597, 39)
fev2026 (3713, 39)
abr2026 (3508, 39)
mai2026 (3419, 39)

In [78]:
lista_dfs = []

for mes, caminho in arquivos.items():
    df_temp = pd.read_csv(caminho)
    df_temp["mes_arquivo"] = mes
    lista_dfs.append(df_temp)

df = pd.concat(lista_dfs, ignore_index=True)

df.shape

(18237, 40)

In [79]:
df.head(3).T

,0,1,2
codigo_pagamento,158146264312025DR801755,158146264312025DR801888,158146264312025OB005334
codigo_pagamento_resumido,2025DR801755,2025DR801888,2025OB005334
data_emissao,2025-12-31,2025-12-31,2025-12-31
codigo_tipo_documento,DR,DR,OB
tipo_documento,Documento de Arrecadação Municipal,Documento de Arrecadação Municipal,Ordem Bancária
tipo_ob,Não se aplica,Não se aplica,OBPIX
extraorcamentario,NÃO,NÃO,NÃO
codigo_orgao_superior,26000,26000,26000
orgao_superior,Ministério da Educação,Ministério da Educação,Ministério da Educação
codigo_orgao,26431,26431,26431
orgao,"Instituto Federal de Educação, Ciência e T","Instituto Federal de Educação, Ciência e T","Instituto Federal de Educação, Ciência e T"
codigo_unidade_gestora,158146,158146,158146
unidade_gestora,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI"
codigo_gestao,26431,26431,26431
gestao,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI"
codigo_favorecido,***.256.903-**,***.320.168-**,***.271.213-**
favorecido,JOSELINA GOMES LIMA,DOMINGOS DA SILVA SOUSA,EDENIA RODRIGUES DE SOUSA
observacao,RETENCAO DE ISS REF. PRESTACAO DE SERVICO DE C...,RETENCAO DE ISS REF. PRESTACAO DE SERVICO DE C...,PAGAMENTO AOS COLABORADORES EXTERNOS QUE EXERC...
processo,NaN,NaN,23187.001586/2025-51
codigo_categoria_despesa,3,3,3
categoria_despesa,DESPESAS CORRENTES,DESPESAS CORRENTES,DESPESAS CORRENTES
codigo_grupo_despesa,3,3,3
grupo_despesa,Outras Despesas Correntes,Outras Despesas Correntes,Outras Despesas Correntes
codigo_modalidade_aplicacao,90,90,90
modalidade_aplicacao,Aplicações Diretas,Aplicações Diretas,Aplicações Diretas
codigo_elemento_despesa,36,36,36
elemento_despesa,Outros Serviços de Terceiros - Pessoa Físic,Outros Serviços de Terceiros - Pessoa Físic,Outros Serviços de Terceiros - Pessoa Físic
codigo_plano_orcamentario,0,0,0
plano_orcamentario,FUNCIONAMENTO DAS INSTITUICOES DA REDE FEDERAL...,FUNCIONAMENTO DAS INSTITUICOES DA REDE FEDERAL...,FUNCIONAMENTO DAS INSTITUICOES DA REDE FEDERAL...
codigo_programa_governo,0,0,0
nome_programa_governo,Sem informação,Sem informação,Sem informação
valor_original_pagamento,"5,00","5,00","143,46"
valor_pagamento_convertido_rs,"5,00","5,00","143,46"
valor_utilizado_conversao,"1,0000","1,0000","1,0000"
mes_referencia,2025-12-01,2025-12-01,2025-12-01
data_extracao,2026-01-20 21:02:10,2026-01-20 21:02:10,2026-01-20 21:02:10
url_origem,https://portaldatransparencia.gov.br/download-...,https://portaldatransparencia.gov.br/download-...,https://portaldatransparencia.gov.br/download-...
hash_dados,a757cceed5e6f9f1dfacf634a8e9ce87,c70666da733497a111c832a85b04cc36,7c31cb7fff822dd894b7519c9db4c52c
data_atualizacao_registro,2026-01-20 18:03:32,2026-01-20 18:03:32,2026-01-20 18:03:32
mes_arquivo,jan2026,jan2026,jan2026

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18237 entries, 0 to 18236
Data columns (total 40 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   codigo_pagamento               18237 non-null  str
 1   codigo_pagamento_resumido      18237 non-null  str
 2   data_emissao                   18237 non-null  str
 3   codigo_tipo_documento          18237 non-null  str
 4   tipo_documento                 18237 non-null  str
 5   tipo_ob                        18237 non-null  str
 6   extraorcamentario              18237 non-null  str
 7   codigo_orgao_superior          18237 non-null  int64
 8   orgao_superior                 18237 non-null  str
 9   codigo_orgao                   18237 non-null  int64
 10  orgao                          18237 non-null  str
 11  codigo_unidade_gestora         18237 non-null  int64
 12  unidade_gestora                18237 non-null  str
 13  codigo_gestao                  18237 non-null  int64
 14  gestao                         18237 non-null  str
 15  codigo_favorecido              18178 non-null  str
 16  favorecido                     18178 non-null  str
 17  observacao                     18237 non-null  str
 18  processo                       16883 non-null  str
 19  codigo_categoria_despesa       18237 non-null  object
 20  categoria_despesa              18237 non-null  str
 21  codigo_grupo_despesa           18237 non-null  str
 22  grupo_despesa                  18237 non-null  str
 23  codigo_modalidade_aplicacao    18237 non-null  str
 24  modalidade_aplicacao           18237 non-null  str
 25  codigo_elemento_despesa        18237 non-null  str
 26  elemento_despesa               18237 non-null  str
 27  codigo_plano_orcamentario      18237 non-null  int64
 28  plano_orcamentario             18237 non-null  str
 29  codigo_programa_governo        18237 non-null  str
 30  nome_programa_governo          18237 non-null  str
 31  valor_original_pagamento       18237 non-null  str
 32  valor_pagamento_convertido_rs  18237 non-null  str
 33  valor_utilizado_conversao      18237 non-null  str
 34  mes_referencia                 18237 non-null  str
 35  data_extracao                  18237 non-null  str
 36  url_origem                     18237 non-null  str
 37  hash_dados                     18237 non-null  str
 38  data_atualizacao_registro      18237 non-null  str
 39  mes_arquivo                    18237 non-null  str
dtypes: int64(5), object(1), str(34)
memory usage: 5.6+ MB

In [81]:
df.isnull().sum().sort_values(ascending=False).head(20)

processo                     1354
codigo_favorecido              59
favorecido                     59
codigo_pagamento                0
tipo_documento                  0
codigo_pagamento_resumido       0
data_emissao                    0
codigo_tipo_documento           0
codigo_orgao_superior           0
extraorcamentario               0
tipo_ob                         0
orgao_superior                  0
codigo_unidade_gestora          0
unidade_gestora                 0
orgao                           0
codigo_orgao                    0
gestao                          0
codigo_gestao                   0
observacao                      0
codigo_categoria_despesa        0
dtype: int64

In [82]:
df["mes_arquivo"].value_counts()

mes_arquivo
jan2026    7597
fev2026    3713
abr2026    3508
mai2026    3419
Name: count, dtype: int64

In [83]:
colunas_valor = [
    "valor_original_pagamento",
    "valor_pagamento_convertido_rs",
    "valor_utilizado_conversao"
]

df[colunas_valor].dtypes

valor_original_pagamento         str
valor_pagamento_convertido_rs    str
valor_utilizado_conversao        str
dtype: object

In [84]:
df[colunas_valor].head(10)

,valor_original_pagamento,valor_pagamento_convertido_rs,valor_utilizado_conversao
0,"5,00","5,00","1,0000"
1,"5,00","5,00","1,0000"
2,"143,46","143,46","1,0000"
3,"143,46","143,46","1,0000"
4,"143,46","143,46","1,0000"
5,"-143,46","-143,46","1,0000"
6,"-2000,00","-2000,00","1,0000"
7,"2000,00","2000,00","1,0000"
8,"-335,89","-335,89","1,0000"
9,"-120,00","-120,00","1,0000"

In [85]:
colunas_data = [
    "data_emissao",
    "mes_referencia",
    "data_extracao",
    "data_atualizacao_registro"
]

for coluna in colunas_data:
    df[coluna] = pd.to_datetime(df[coluna], errors="coerce")

In [86]:
df[colunas_data].dtypes

data_emissao                 datetime64[us]
mes_referencia               datetime64[us]
data_extracao                datetime64[us]
data_atualizacao_registro    datetime64[us]
dtype: object

In [87]:
def converter_valor(serie):
    if pd.api.types.is_numeric_dtype(serie):
        return serie

    serie_texto = serie.astype(str).str.strip()

    tem_virgula = serie_texto.str.contains(",", regex=False, na=False).any()

    if tem_virgula:
        serie_texto = (
            serie_texto
            .str.replace(".", "", regex=False)
            .str.replace(",", ".", regex=False)
        )

    serie_texto = serie_texto.replace({
        "": pd.NA,
        "nan": pd.NA,
        "None": pd.NA
    })

    return pd.to_numeric(serie_texto, errors="coerce")


for coluna in colunas_valor:
    df[coluna] = converter_valor(df[coluna])

In [88]:
df[colunas_data + colunas_valor].info()

<class 'pandas.DataFrame'>
RangeIndex: 18237 entries, 0 to 18236
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   data_emissao                   18237 non-null  datetime64[us]
 1   mes_referencia                 18237 non-null  datetime64[us]
 2   data_extracao                  18237 non-null  datetime64[us]
 3   data_atualizacao_registro      18237 non-null  datetime64[us]
 4   valor_original_pagamento       18237 non-null  float64
 5   valor_pagamento_convertido_rs  18237 non-null  float64
 6   valor_utilizado_conversao      18237 non-null  float64
dtypes: datetime64[us](4), float64(3)
memory usage: 997.5 KB

In [89]:
df[colunas_data + colunas_valor].isnull().sum()

data_emissao                     0
mes_referencia                   0
data_extracao                    0
data_atualizacao_registro        0
valor_original_pagamento         0
valor_pagamento_convertido_rs    0
valor_utilizado_conversao        0
dtype: int64

In [90]:
df["ano_emissao"] = df["data_emissao"].dt.year
df["mes_emissao"] = df["data_emissao"].dt.month
df["dia_emissao"] = df["data_emissao"].dt.day
df["nome_mes_emissao"] = df["data_emissao"].dt.month_name()

In [91]:
df.duplicated().sum()

np.int64(0)

In [92]:
df.isnull().sum().sort_values(ascending=False).head(10)

processo                     1354
codigo_favorecido              59
favorecido                     59
codigo_pagamento                0
tipo_documento                  0
tipo_ob                         0
extraorcamentario               0
codigo_orgao_superior           0
orgao_superior                  0
codigo_pagamento_resumido       0
dtype: int64

In [93]:
df_tratado = df.copy()

In [94]:
df_tratado["processo"] = df_tratado["processo"].fillna("Não informado")
df_tratado["codigo_favorecido"] = df_tratado["codigo_favorecido"].fillna("Não informado")
df_tratado["favorecido"] = df_tratado["favorecido"].fillna("Não informado")

In [95]:
df_tratado[["processo", "codigo_favorecido", "favorecido"]].isnull().sum()

processo             0
codigo_favorecido    0
favorecido           0
dtype: int64

In [96]:
mapa_meses = {
    1: "Janeiro",
    2: "Fevereiro",
    3: "Março",
    4: "Abril",
    5: "Maio",
    6: "Junho",
    7: "Julho",
    8: "Agosto",
    9: "Setembro",
    10: "Outubro",
    11: "Novembro",
    12: "Dezembro"
}

df_tratado["mes_emissao_nome"] = df_tratado["mes_emissao"].map(mapa_meses)

In [97]:
df_tratado.shape

(18237, 45)

In [98]:
df_tratado.isnull().sum().sort_values(ascending=False).head(10)

codigo_pagamento             0
codigo_pagamento_resumido    0
data_emissao                 0
codigo_tipo_documento        0
tipo_documento               0
tipo_ob                      0
extraorcamentario            0
codigo_orgao_superior        0
orgao_superior               0
codigo_orgao                 0
dtype: int64

In [99]:
df_tratado.head(3).T

,0,1,2
codigo_pagamento,158146264312025DR801755,158146264312025DR801888,158146264312025OB005334
codigo_pagamento_resumido,2025DR801755,2025DR801888,2025OB005334
data_emissao,2025-12-31 00:00:00,2025-12-31 00:00:00,2025-12-31 00:00:00
codigo_tipo_documento,DR,DR,OB
tipo_documento,Documento de Arrecadação Municipal,Documento de Arrecadação Municipal,Ordem Bancária
tipo_ob,Não se aplica,Não se aplica,OBPIX
extraorcamentario,NÃO,NÃO,NÃO
codigo_orgao_superior,26000,26000,26000
orgao_superior,Ministério da Educação,Ministério da Educação,Ministério da Educação
codigo_orgao,26431,26431,26431
orgao,"Instituto Federal de Educação, Ciência e T","Instituto Federal de Educação, Ciência e T","Instituto Federal de Educação, Ciência e T"
codigo_unidade_gestora,158146,158146,158146
unidade_gestora,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI"
codigo_gestao,26431,26431,26431
gestao,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI","INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI"
codigo_favorecido,***.256.903-**,***.320.168-**,***.271.213-**
favorecido,JOSELINA GOMES LIMA,DOMINGOS DA SILVA SOUSA,EDENIA RODRIGUES DE SOUSA
observacao,RETENCAO DE ISS REF. PRESTACAO DE SERVICO DE C...,RETENCAO DE ISS REF. PRESTACAO DE SERVICO DE C...,PAGAMENTO AOS COLABORADORES EXTERNOS QUE EXERC...
processo,Não informado,Não informado,23187.001586/2025-51
codigo_categoria_despesa,3,3,3
categoria_despesa,DESPESAS CORRENTES,DESPESAS CORRENTES,DESPESAS CORRENTES
codigo_grupo_despesa,3,3,3
grupo_despesa,Outras Despesas Correntes,Outras Despesas Correntes,Outras Despesas Correntes
codigo_modalidade_aplicacao,90,90,90
modalidade_aplicacao,Aplicações Diretas,Aplicações Diretas,Aplicações Diretas
codigo_elemento_despesa,36,36,36
elemento_despesa,Outros Serviços de Terceiros - Pessoa Físic,Outros Serviços de Terceiros - Pessoa Físic,Outros Serviços de Terceiros - Pessoa Físic
codigo_plano_orcamentario,0,0,0
plano_orcamentario,FUNCIONAMENTO DAS INSTITUICOES DA REDE FEDERAL...,FUNCIONAMENTO DAS INSTITUICOES DA REDE FEDERAL...,FUNCIONAMENTO DAS INSTITUICOES DA REDE FEDERAL...
codigo_programa_governo,0,0,0
nome_programa_governo,Sem informação,Sem informação,Sem informação
valor_original_pagamento,5.0,5.0,143.46
valor_pagamento_convertido_rs,5.0,5.0,143.46
valor_utilizado_conversao,1.0,1.0,1.0
mes_referencia,2025-12-01 00:00:00,2025-12-01 00:00:00,2025-12-01 00:00:00
data_extracao,2026-01-20 21:02:10,2026-01-20 21:02:10,2026-01-20 21:02:10
url_origem,https://portaldatransparencia.gov.br/download-...,https://portaldatransparencia.gov.br/download-...,https://portaldatransparencia.gov.br/download-...
hash_dados,a757cceed5e6f9f1dfacf634a8e9ce87,c70666da733497a111c832a85b04cc36,7c31cb7fff822dd894b7519c9db4c52c
data_atualizacao_registro,2026-01-20 18:03:32,2026-01-20 18:03:32,2026-01-20 18:03:32
mes_arquivo,jan2026,jan2026,jan2026
ano_emissao,2025,2025,2025
mes_emissao,12,12,12
dia_emissao,31,31,31
nome_mes_emissao,December,December,December
mes_emissao_nome,Dezembro,Dezembro,Dezembro

In [100]:
print("Tamanho da base tratada:", df_tratado.shape)
print("Total de nulos:", df_tratado.isnull().sum().sum())
print("Total de duplicatas:", df_tratado.duplicated().sum())

Tamanho da base tratada: (18237, 45)
Total de nulos: 0
Total de duplicatas: 0

In [101]:
df_tratado["valor_pagamento_convertido_rs"].describe()

count    1.823700e+04
mean     1.729401e+04
std      4.407290e+05
min     -3.971374e+04
25%      6.119000e+01
50%      2.000000e+02
75%      8.125000e+02
max      3.221460e+07
Name: valor_pagamento_convertido_rs, dtype: float64

In [102]:
df_tratado.sort_values(
    by="valor_pagamento_convertido_rs",
    ascending=False
)[[
    "mes_arquivo",
    "data_emissao",
    "favorecido",
    "categoria_despesa",
    "grupo_despesa",
    "elemento_despesa",
    "valor_pagamento_convertido_rs"
]].head(10)

,mes_arquivo,data_emissao,favorecido,categoria_despesa,grupo_despesa,elemento_despesa,valor_pagamento_convertido_rs
10661,fev2026,2026-01-02,BANCO DO BRASIL SA,DESPESAS CORRENTES,Múltiplo,Múltiplo,32214601.00
2886,jan2026,2025-12-01,BANCO DO BRASIL SA,DESPESAS CORRENTES,Múltiplo,Múltiplo,27184435.67
14844,mai2026,2026-04-01,BANCO DO BRASIL SA,DESPESAS CORRENTES,Múltiplo,Múltiplo,20169049.03
14435,abr2026,2026-03-02,BANCO DO BRASIL SA,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,19941849.39
10614,fev2026,2026-01-20,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",DESPESAS CORRENTES,Pessoal e Encargos Sociais,Múltiplo,12264146.83
10657,fev2026,2026-01-02,CAIXA ECONOMICA FEDERAL,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,11336941.93
2884,jan2026,2025-12-01,CAIXA ECONOMICA FEDERAL,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,9292540.23
7868,fev2026,2026-01-15,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",DESPESAS CORRENTES,Pessoal e Encargos Sociais,Obrigações Patronais,6760221.58
17245,mai2026,2026-04-16,Não informado,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Obrigações Patronais,6753566.06
14861,mai2026,2026-04-01,CAIXA ECONOMICA FEDERAL,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,6718309.80

In [103]:
df_tratado.sort_values(
    by="valor_pagamento_convertido_rs",
    ascending=True
)[[
    "mes_arquivo",
    "data_emissao",
    "favorecido",
    "categoria_despesa",
    "grupo_despesa",
    "elemento_despesa",
    "valor_pagamento_convertido_rs"
]].head(10)

,mes_arquivo,data_emissao,favorecido,categoria_despesa,grupo_despesa,elemento_despesa,valor_pagamento_convertido_rs
2868,jan2026,2025-12-31,SECRETARIA DO TURISMO DO ESTADO DO PIAUI,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,-39713.74
14410,abr2026,2026-03-31,PIAUI SECRETARIA DO PLANEJAMENTO SEPLAN,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,-38842.02
2864,jan2026,2025-12-22,MUNICIPIO DE SAO GONCALO DO AMARANTE,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,-29969.04
2867,jan2026,2025-12-30,MUNICIPIO DE PICOS,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,-28480.94
14413,abr2026,2026-03-31,PIAUI SECRETARIA DE EDUCACAO,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,-28363.87
10716,fev2026,2026-01-07,SERVICO FEDERAL DE PROCESSAMENTO DE DADOS (SER...,Sem informação,Sem informação,Sem informação,-23876.92
10707,fev2026,2026-01-05,SERVICO FEDERAL DE PROCESSAMENTO DE DADOS (SER...,Sem informação,Sem informação,Sem informação,-23876.92
7606,fev2026,2026-01-23,EQUATORIAL PIAUI DISTRIBUIDORA DE ENERGIA S.A,Sem informação,Sem informação,Sem informação,-23074.02
14408,abr2026,2026-03-31,PIAUI SECRETARIA DO PLANEJAMENTO SEPLAN,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,-21635.78
2866,jan2026,2025-12-29,PIAUI SECRETARIA DO PLANEJAMENTO SEPLAN,DESPESAS CORRENTES,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,-21599.33

In [104]:
df_tratado["tipo_valor"] = df_tratado["valor_pagamento_convertido_rs"].apply(
    lambda x: "Valor negativo / ajuste" if x < 0 else "Valor positivo"
)

resumo_tipo_valor = df_tratado.groupby("tipo_valor").agg(
    qtd_registros=("codigo_pagamento", "count"),
    valor_total=("valor_pagamento_convertido_rs", "sum"),
    valor_medio=("valor_pagamento_convertido_rs", "mean")
).reset_index()

resumo_tipo_valor["valor_total"] = resumo_tipo_valor["valor_total"].round(2)
resumo_tipo_valor["valor_medio"] = resumo_tipo_valor["valor_medio"].round(2)

resumo_tipo_valor

                tipo_valor  qtd_registros   valor_total  valor_medio
0  Valor negativo / ajuste            499 -7.358793e+05     -1474.71
1           Valor positivo          17738  3.161268e+08     17822.01

In [105]:
df_positivos = df_tratado[df_tratado["valor_pagamento_convertido_rs"] > 0].copy()
df_negativos = df_tratado[df_tratado["valor_pagamento_convertido_rs"] < 0].copy()

print("Pagamentos positivos:", df_positivos.shape)
print("Valores negativos/ajustes:", df_negativos.shape)

Pagamentos positivos: (17711, 46)
Valores negativos/ajustes: (499, 46)

In [106]:
df_tratado["tipo_valor"] = df_tratado["valor_pagamento_convertido_rs"].apply(
    lambda x: "Valor negativo / ajuste" if x < 0 
    else "Valor zerado" if x == 0 
    else "Valor positivo"
)

resumo_tipo_valor = df_tratado.groupby("tipo_valor").agg(
    qtd_registros=("codigo_pagamento", "count"),
    valor_total=("valor_pagamento_convertido_rs", "sum"),
    valor_medio=("valor_pagamento_convertido_rs", "mean")
).reset_index()

resumo_tipo_valor["valor_total"] = resumo_tipo_valor["valor_total"].round(2)
resumo_tipo_valor["valor_medio"] = resumo_tipo_valor["valor_medio"].round(2)

resumo_tipo_valor

                tipo_valor  qtd_registros   valor_total  valor_medio
0  Valor negativo / ajuste            499 -7.358793e+05     -1474.71
1           Valor positivo          17711  3.161268e+08     17849.18
2             Valor zerado             27  0.000000e+00         0.00

In [107]:
df_positivos = df_tratado[df_tratado["valor_pagamento_convertido_rs"] > 0].copy()
df_negativos = df_tratado[df_tratado["valor_pagamento_convertido_rs"] < 0].copy()
df_zerados = df_tratado[df_tratado["valor_pagamento_convertido_rs"] == 0].copy()

print("Pagamentos positivos:", df_positivos.shape)
print("Valores negativos/ajustes:", df_negativos.shape)
print("Valores zerados:", df_zerados.shape)

Pagamentos positivos: (17711, 46)
Valores negativos/ajustes: (499, 46)
Valores zerados: (27, 46)

In [108]:
pd.options.display.float_format = "{:,.2f}".format

In [109]:
resumo_tipo_valor

                tipo_valor  qtd_registros    valor_total  valor_medio
0  Valor negativo / ajuste            499    -735,879.32    -1,474.71
1           Valor positivo          17711 316,126,829.94    17,849.18
2             Valor zerado             27           0.00         0.00

In [110]:
resumo_mes = df_positivos.groupby("mes_arquivo").agg(
    qtd_pagamentos=("codigo_pagamento", "count"),
    valor_total=("valor_pagamento_convertido_rs", "sum"),
    valor_medio=("valor_pagamento_convertido_rs", "mean")
).reset_index()

resumo_mes["valor_total"] = resumo_mes["valor_total"].round(2)
resumo_mes["valor_medio"] = resumo_mes["valor_medio"].round(2)

resumo_mes

  mes_arquivo  qtd_pagamentos   valor_total  valor_medio
0     abr2026            3436 74,325,396.05    21,631.37
1     fev2026            3677 85,442,377.64    23,236.98
2     jan2026            7244 88,456,481.52    12,211.00
3     mai2026            3354 67,902,574.73    20,245.25

In [111]:
ordem_meses = {
    "jan2026": 1,
    "fev2026": 2,
    "abr2026": 4,
    "mai2026": 5
}

resumo_mes["ordem_mes"] = resumo_mes["mes_arquivo"].map(ordem_meses)

resumo_mes = resumo_mes.sort_values("ordem_mes").drop(columns="ordem_mes")

resumo_mes

  mes_arquivo  qtd_pagamentos   valor_total  valor_medio
2     jan2026            7244 88,456,481.52    12,211.00
1     fev2026            3677 85,442,377.64    23,236.98
0     abr2026            3436 74,325,396.05    21,631.37
3     mai2026            3354 67,902,574.73    20,245.25

In [112]:
top_favorecidos = df_positivos.groupby("favorecido").agg(
    qtd_pagamentos=("codigo_pagamento", "count"),
    valor_total=("valor_pagamento_convertido_rs", "sum"),
    valor_medio=("valor_pagamento_convertido_rs", "mean")
).reset_index()

top_favorecidos["valor_total"] = top_favorecidos["valor_total"].round(2)
top_favorecidos["valor_medio"] = top_favorecidos["valor_medio"].round(2)

top_favorecidos = top_favorecidos.sort_values(
    by="valor_total",
    ascending=False
)

top_favorecidos.head(10)

,favorecido,qtd_pagamentos,valor_total,valor_medio
487,BANCO DO BRASIL SA,959,"127,570,406.91","133,024.41"
1639,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",1888,"76,723,712.91","40,637.56"
573,CAIXA ECONOMICA FEDERAL,50,"39,013,500.81","780,270.02"
1358,"FUNDACAO DE AMPARO A PESQUISA, INOVACAO, ENSIN...",13,"16,346,497.78","1,257,422.91"
3174,Não informado,55,"10,901,476.55","198,208.66"
1356,FUNDACAO CIDADANIA,1,"5,000,000.00","5,000,000.00"
488,BANCO SANTANDER (BRASIL) S.A.,12,"3,231,266.16","269,272.18"
3306,PLANO EXECUTIVO FEDERAL,22,"2,995,445.92","136,156.63"
3295,PERFORMANCE SERVICOS DE ENGENHARIA LTDA,11,"2,147,996.71","195,272.43"
3648,SERVFAZ SERVICOS DE MAO DE OBRA LTDA,335,"1,923,114.96","5,740.64"

In [113]:
favorecidos_top5 = top_favorecidos.head(5)["favorecido"].tolist()

analise_top_favorecidos = df_positivos[
    df_positivos["favorecido"].isin(favorecidos_top5)
].groupby([
    "favorecido",
    "grupo_despesa",
    "elemento_despesa"
]).agg(
    qtd_pagamentos=("codigo_pagamento", "count"),
    valor_total=("valor_pagamento_convertido_rs", "sum"),
    valor_medio=("valor_pagamento_convertido_rs", "mean")
).reset_index()

analise_top_favorecidos["valor_total"] = analise_top_favorecidos["valor_total"].round(2)
analise_top_favorecidos["valor_medio"] = analise_top_favorecidos["valor_medio"].round(2)

analise_top_favorecidos.sort_values(
    by="valor_total",
    ascending=False
).head(20)

,favorecido,grupo_despesa,elemento_despesa,qtd_pagamentos,valor_total,valor_medio
0,BANCO DO BRASIL SA,Múltiplo,Múltiplo,14,"79,962,887.48","5,711,634.82"
28,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,32,"36,159,808.47","1,129,994.01"
26,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",Pessoal e Encargos Sociais,Obrigações Patronais,16,"27,746,701.93","1,734,168.87"
18,CAIXA ECONOMICA FEDERAL,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,3,"27,347,791.96","9,115,930.65"
11,BANCO DO BRASIL SA,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,5,"20,037,744.71","4,007,548.94"
25,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",Pessoal e Encargos Sociais,Múltiplo,2,"12,284,818.31","6,142,409.16"
21,"FUNDACAO DE AMPARO A PESQUISA, INOVACAO, ENSIN...",Outras Despesas Correntes,Outros Serviços de Terceiros - Pessoa Juríd,11,"11,726,497.78","1,066,045.25"
9,BANCO DO BRASIL SA,Pessoal e Encargos Sociais,Múltiplo,6,"10,862,633.41","1,810,438.90"
8,BANCO DO BRASIL SA,Pessoal e Encargos Sociais,"Aposentadorias, Reserva Remunerada e Reformas",7,"8,856,468.90","1,265,209.84"
35,Não informado,Pessoal e Encargos Sociais,Obrigações Patronais,5,"7,052,538.66","1,410,507.73"
13,CAIXA ECONOMICA FEDERAL,Múltiplo,Múltiplo,1,"6,665,815.45","6,665,815.45"
16,CAIXA ECONOMICA FEDERAL,Pessoal e Encargos Sociais,Múltiplo,7,"4,349,721.84","621,388.83"
34,Não informado,Pessoal e Encargos Sociais,Múltiplo,2,"3,612,698.25","1,806,349.12"
20,"FUNDACAO DE AMPARO A PESQUISA, INOVACAO, ENSIN...",Múltiplo,Múltiplo,1,"3,000,000.00","3,000,000.00"
4,BANCO DO BRASIL SA,Outras Despesas Correntes,Múltiplo,55,"1,925,319.02","35,005.80"
10,BANCO DO BRASIL SA,Pessoal e Encargos Sociais,Pensões,15,"1,780,269.98","118,684.67"
22,"FUNDACAO DE AMPARO A PESQUISA, INOVACAO, ENSIN...",Sem informação,Sem informação,1,"1,620,000.00","1,620,000.00"
3,BANCO DO BRASIL SA,Outras Despesas Correntes,Locação de Mão-de-Obra,445,"1,540,953.76","3,462.82"
6,BANCO DO BRASIL SA,Outras Despesas Correntes,Outros Serviços de Terceiros - Pessoa Juríd,135,"1,247,139.68","9,238.07"
1,BANCO DO BRASIL SA,Outras Despesas Correntes,Auxílio Financeiro a Estudantes,145,"618,472.20","4,265.33"

In [114]:
df_positivos[df_positivos["favorecido"] == "Não informado"][[
    "mes_arquivo",
    "data_emissao",
    "favorecido",
    "observacao",
    "grupo_despesa",
    "elemento_despesa",
    "valor_pagamento_convertido_rs"
]].sort_values(
    by="valor_pagamento_convertido_rs",
    ascending=False
).head(20)

,mes_arquivo,data_emissao,favorecido,observacao,grupo_despesa,elemento_despesa,valor_pagamento_convertido_rs
17245,mai2026,2026-04-16,Não informado,"RECOLHIMENTO DE PSSS FOLHA DE PESSOAL ATIVO, R...",Pessoal e Encargos Sociais,Obrigações Patronais,"6,753,566.06"
17243,mai2026,2026-04-16,Não informado,"RECOLHIMENTO DE PSSS FOLHA DE PESSOAL ATIVO, R...",Pessoal e Encargos Sociais,Múltiplo,"3,376,783.03"
17294,mai2026,2026-04-20,Não informado,RECOLHIMENTO DE CDT- DARF NUMERADO FOLHA DE PE...,Pessoal e Encargos Sociais,Obrigações Patronais,"262,488.14"
17244,mai2026,2026-04-16,Não informado,"RECOLHIMENTO DE PSSS FOLHA DE PESSOAL INATIVO,...",Pessoal e Encargos Sociais,Múltiplo,"235,915.22"
17292,mai2026,2026-04-20,Não informado,RECOLHIMENTO DE CDT- DARF NUMERADO FOLHA DE PE...,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,"140,409.55"
17236,mai2026,2026-04-02,Não informado,RETENCAO DE IMPOSTOS FEDERAIS DO(S) INSTR.(S) ...,Investimentos,Equipamentos e Material Permanente,"16,052.40"
17295,mai2026,2026-04-20,Não informado,RECOLHIMENTO DE CDT- DARF NUMERADO FOLHA DE PE...,Pessoal e Encargos Sociais,Obrigações Patronais,"13,124.40"
17296,mai2026,2026-04-20,Não informado,RECOLHIMENTO DE CDT- DARF NUMERADO FOLHA DE PE...,Pessoal e Encargos Sociais,Obrigações Patronais,"11,680.03"
17300,mai2026,2026-04-20,Não informado,RECOLHIMENTO DE CDT- DARF NUMERADO FOLHA DE PE...,Pessoal e Encargos Sociais,Obrigações Patronais,"11,680.03"
17260,mai2026,2026-04-17,Não informado,"RETENCAO DO INSS SOBRE FOLHA DE PAGAMENTO, CON...",Outras Despesas Correntes,Locação de Mão-de-Obra,"5,288.03"
17263,mai2026,2026-04-17,Não informado,RETENCAO DE TRIBUTOS FEDERAIS INCIDENTES SOBRE...,Outras Despesas Correntes,Locação de Mão-de-Obra,"5,078.27"
17261,mai2026,2026-04-17,Não informado,RETENCAO DE TRIBUTOS FEDERAIS INCIDENTES SOBRE...,Outras Despesas Correntes,Locação de Mão-de-Obra,"4,542.90"
17249,mai2026,2026-04-17,Não informado,RETENCAO DE TRIBUTOS FEDERAIS INCIDENTES SOBRE...,Outras Despesas Correntes,Locação de Mão-de-Obra,"4,542.90"
17276,mai2026,2026-04-20,Não informado,"RETENCAO DE INSS SOBRE NFSE 47217, REFERENTE A...",Outras Despesas Correntes,Locação de Mão-de-Obra,"4,427.80"
17285,mai2026,2026-04-20,Não informado,"RETENCOES PREVIDENCIARIAS SOBRE NF 158, REFERE...",Outras Despesas Correntes,Locação de Mão-de-Obra,"4,124.45"
17268,mai2026,2026-04-17,Não informado,"RETENCAO DO INSS SOBRE FOLHA DE PAGAMENTO, CON...",Outras Despesas Correntes,Outros Serviços de Terceiros - Pessoa Juríd,"4,028.25"
17277,mai2026,2026-04-20,Não informado,RETENCAO DE INSS DO(S) INSTR.(S) DE COBRANCA(S...,Outras Despesas Correntes,Locação de Mão-de-Obra,"3,710.52"
17248,mai2026,2026-04-17,Não informado,RETENCAO DE TRIBUTOS FEDERAIS INCIDENTES SOBRE...,Outras Despesas Correntes,Outros Serviços de Terceiros - Pessoa Juríd,"2,761.98"
17256,mai2026,2026-04-17,Não informado,"RETENCAO DO INSS SOBRE FOLHA DE PAGAMENTO, CON...",Outras Despesas Correntes,Locação de Mão-de-Obra,"2,752.44"
17267,mai2026,2026-04-17,Não informado,RETENCAO DE INSS - SERVFAZ SERVICOS DE MAO DE ...,Outras Despesas Correntes,Locação de Mão-de-Obra,"2,752.44"

In [115]:
resumo_grupo = df_positivos.groupby("grupo_despesa").agg(
    qtd_pagamentos=("codigo_pagamento", "count"),
    valor_total=("valor_pagamento_convertido_rs", "sum"),
    valor_medio=("valor_pagamento_convertido_rs", "mean")
).reset_index()

resumo_grupo["valor_total"] = resumo_grupo["valor_total"].round(2)
resumo_grupo["valor_medio"] = resumo_grupo["valor_medio"].round(2)

resumo_grupo = resumo_grupo.sort_values(
    by="valor_total",
    ascending=False
)

resumo_grupo

                grupo_despesa  qtd_pagamentos    valor_total  valor_medio
3  Pessoal e Encargos Sociais             173 169,402,128.67   979,203.06
1                    Múltiplo              27  90,974,702.11 3,369,433.41
2   Outras Despesas Correntes           16622  45,301,960.32     2,725.42
0               Investimentos             150   6,716,566.64    44,777.11
4              Sem informação             739   3,731,472.20     5,049.35

In [116]:
total_geral = df_positivos["valor_pagamento_convertido_rs"].sum()

resumo_grupo["participacao_percentual"] = (
    resumo_grupo["valor_total"] / total_geral * 100
).round(2)

resumo_grupo

,grupo_despesa,qtd_pagamentos,valor_total,valor_medio,participacao_percentual
3,Pessoal e Encargos Sociais,173,"169,402,128.67","979,203.06",53.59
1,Múltiplo,27,"90,974,702.11","3,369,433.41",28.78
2,Outras Despesas Correntes,16622,"45,301,960.32","2,725.42",14.33
0,Investimentos,150,"6,716,566.64","44,777.11",2.12
4,Sem informação,739,"3,731,472.20","5,049.35",1.18

In [117]:
resumo_elemento = df_positivos.groupby(["grupo_despesa", "elemento_despesa"]).agg(
    qtd_pagamentos=("codigo_pagamento", "count"),
    valor_total=("valor_pagamento_convertido_rs", "sum"),
    valor_medio=("valor_pagamento_convertido_rs", "mean")
).reset_index()

resumo_elemento["valor_total"] = resumo_elemento["valor_total"].round(2)
resumo_elemento["valor_medio"] = resumo_elemento["valor_medio"].round(2)

resumo_elemento = resumo_elemento.sort_values(
    by="valor_total",
    ascending=False
)

resumo_elemento.head(15)

,grupo_despesa,elemento_despesa,qtd_pagamentos,valor_total,valor_medio
2,Múltiplo,Múltiplo,27,"90,974,702.11","3,369,433.41"
26,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,66,"89,224,628.59","1,351,888.31"
23,Pessoal e Encargos Sociais,Obrigações Patronais,21,"34,799,240.59","1,657,106.69"
22,Pessoal e Encargos Sociais,Múltiplo,19,"31,885,555.08","1,678,187.11"
17,Outras Despesas Correntes,Outros Serviços de Terceiros - Pessoa Juríd,989,"21,366,463.97","21,604.11"
9,Outras Despesas Correntes,Locação de Mão-de-Obra,2572,"12,504,466.57","4,861.77"
20,Pessoal e Encargos Sociais,"Aposentadorias, Reserva Remunerada e Reformas",23,"9,264,047.00","402,784.65"
1,Investimentos,Obras e Instalações,73,"4,825,082.24","66,097.02"
27,Sem informação,Sem informação,739,"3,731,472.20","5,049.35"
10,Outras Despesas Correntes,Material de Consumo,1420,"3,105,872.53","2,187.23"
24,Pessoal e Encargos Sociais,Pensões,36,"2,754,971.19","76,526.98"
12,Outras Despesas Correntes,Múltiplo,90,"2,332,465.48","25,916.28"
3,Outras Despesas Correntes,Auxílio Financeiro a Estudantes,6284,"2,213,540.41",352.25
0,Investimentos,Equipamentos e Material Permanente,77,"1,891,484.40","24,564.73"
21,Pessoal e Encargos Sociais,Contribuição a Entidades Fechadas de Previd,6,"1,464,872.58","244,145.43"

In [118]:
resumo_elemento_top15 = resumo_elemento.head(15).copy()

total_positivos = df_positivos["valor_pagamento_convertido_rs"].sum()

resumo_elemento_top15["participacao_percentual"] = (
    resumo_elemento_top15["valor_total"] / total_positivos * 100
).round(2)

resumo_elemento_top15

,grupo_despesa,elemento_despesa,qtd_pagamentos,valor_total,valor_medio,participacao_percentual
2,Múltiplo,Múltiplo,27,"90,974,702.11","3,369,433.41",28.78
26,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,66,"89,224,628.59","1,351,888.31",28.22
23,Pessoal e Encargos Sociais,Obrigações Patronais,21,"34,799,240.59","1,657,106.69",11.01
22,Pessoal e Encargos Sociais,Múltiplo,19,"31,885,555.08","1,678,187.11",10.09
17,Outras Despesas Correntes,Outros Serviços de Terceiros - Pessoa Juríd,989,"21,366,463.97","21,604.11",6.76
9,Outras Despesas Correntes,Locação de Mão-de-Obra,2572,"12,504,466.57","4,861.77",3.96
20,Pessoal e Encargos Sociais,"Aposentadorias, Reserva Remunerada e Reformas",23,"9,264,047.00","402,784.65",2.93
1,Investimentos,Obras e Instalações,73,"4,825,082.24","66,097.02",1.53
27,Sem informação,Sem informação,739,"3,731,472.20","5,049.35",1.18
10,Outras Despesas Correntes,Material de Consumo,1420,"3,105,872.53","2,187.23",0.98
24,Pessoal e Encargos Sociais,Pensões,36,"2,754,971.19","76,526.98",0.87
12,Outras Despesas Correntes,Múltiplo,90,"2,332,465.48","25,916.28",0.74
3,Outras Despesas Correntes,Auxílio Financeiro a Estudantes,6284,"2,213,540.41",352.25,0.70
0,Investimentos,Equipamentos e Material Permanente,77,"1,891,484.40","24,564.73",0.60
21,Pessoal e Encargos Sociais,Contribuição a Entidades Fechadas de Previd,6,"1,464,872.58","244,145.43",0.46

In [119]:
resumo_mes_grupo = df_positivos.groupby(["mes_arquivo", "grupo_despesa"]).agg(
    qtd_pagamentos=("codigo_pagamento", "count"),
    valor_total=("valor_pagamento_convertido_rs", "sum"),
    valor_medio=("valor_pagamento_convertido_rs", "mean")
).reset_index()

resumo_mes_grupo["valor_total"] = resumo_mes_grupo["valor_total"].round(2)
resumo_mes_grupo["valor_medio"] = resumo_mes_grupo["valor_medio"].round(2)

ordem_meses = {
    "jan2026": 1,
    "fev2026": 2,
    "abr2026": 4,
    "mai2026": 5
}

resumo_mes_grupo["ordem_mes"] = resumo_mes_grupo["mes_arquivo"].map(ordem_meses)

resumo_mes_grupo = resumo_mes_grupo.sort_values(
    by=["ordem_mes", "valor_total"],
    ascending=[True, False]
).drop(columns="ordem_mes")

resumo_mes_grupo

,mes_arquivo,grupo_despesa,qtd_pagamentos,valor_total,valor_medio
13,jan2026,Pessoal e Encargos Sociais,50,"47,023,745.74","940,474.91"
11,jan2026,Múltiplo,3,"27,375,263.56","9,125,087.85"
12,jan2026,Outras Despesas Correntes,7058,"12,010,020.72","1,701.62"
10,jan2026,Investimentos,34,"1,875,220.91","55,153.56"
14,jan2026,Sem informação,99,"172,230.59","1,739.70"
8,fev2026,Pessoal e Encargos Sociais,45,"44,600,192.29","991,115.38"
6,fev2026,Múltiplo,14,"32,930,164.87","2,352,154.63"
7,fev2026,Outras Despesas Correntes,3551,"6,504,823.24","1,831.83"
5,fev2026,Investimentos,40,"1,251,020.53","31,275.51"
9,fev2026,Sem informação,27,"156,176.71","5,784.32"
3,abr2026,Pessoal e Encargos Sociais,37,"45,334,348.09","1,225,252.65"
2,abr2026,Outras Despesas Correntes,2807,"14,716,010.70","5,242.61"
1,abr2026,Múltiplo,5,"9,708,834.96","1,941,766.99"
4,abr2026,Sem informação,567,"3,289,526.42","5,801.63"
0,abr2026,Investimentos,20,"1,276,675.88","63,833.79"
18,mai2026,Pessoal e Encargos Sociais,41,"32,443,842.55","791,313.23"
16,mai2026,Múltiplo,5,"20,960,438.72","4,192,087.74"
17,mai2026,Outras Despesas Correntes,3206,"12,071,105.66","3,765.16"
15,mai2026,Investimentos,56,"2,313,649.32","41,315.17"
19,mai2026,Sem informação,46,"113,538.48","2,468.23"

In [120]:
pivot_mes_grupo = resumo_mes_grupo.pivot_table(
    index="mes_arquivo",
    columns="grupo_despesa",
    values="valor_total",
    aggfunc="sum",
    fill_value=0
).reset_index()

ordem_meses = {
    "jan2026": 1,
    "fev2026": 2,
    "abr2026": 4,
    "mai2026": 5
}

pivot_mes_grupo["ordem_mes"] = pivot_mes_grupo["mes_arquivo"].map(ordem_meses)

pivot_mes_grupo = pivot_mes_grupo.sort_values("ordem_mes").drop(columns="ordem_mes")

pivot_mes_grupo

grupo_despesa,mes_arquivo,Investimentos,Múltiplo,Outras Despesas Correntes,Pessoal e Encargos Sociais,Sem informação
2,jan2026,"1,875,220.91","27,375,263.56","12,010,020.72","47,023,745.74","172,230.59"
1,fev2026,"1,251,020.53","32,930,164.87","6,504,823.24","44,600,192.29","156,176.71"
0,abr2026,"1,276,675.88","9,708,834.96","14,716,010.70","45,334,348.09","3,289,526.42"
3,mai2026,"2,313,649.32","20,960,438.72","12,071,105.66","32,443,842.55","113,538.48"

In [121]:
maiores_pagamentos = df_positivos[[
    "mes_arquivo",
    "data_emissao",
    "favorecido",
    "grupo_despesa",
    "elemento_despesa",
    "observacao",
    "valor_pagamento_convertido_rs"
]].sort_values(
    by="valor_pagamento_convertido_rs",
    ascending=False
)

maiores_pagamentos.head(15)

,mes_arquivo,data_emissao,favorecido,grupo_despesa,elemento_despesa,observacao,valor_pagamento_convertido_rs
10661,fev2026,2026-01-02,BANCO DO BRASIL SA,Múltiplo,Múltiplo,"PAGAMENTO FOLHA DE PESSOAL ATIVO, INATIVO REF....","32,214,601.00"
2886,jan2026,2025-12-01,BANCO DO BRASIL SA,Múltiplo,Múltiplo,"PAGAMENTO FOLHA DE PESSOAL ATIVO, INATIVO REF....","27,184,435.67"
14844,mai2026,2026-04-01,BANCO DO BRASIL SA,Múltiplo,Múltiplo,"PAGAMENTO FOLHA DE PESSOAL ATIVO, INATIVO REF....","20,169,049.03"
14435,abr2026,2026-03-02,BANCO DO BRASIL SA,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,"PAGAMENTO FOLHA DE PESSOAL ATIVO, INATIVO REF....","19,941,849.39"
10614,fev2026,2026-01-20,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",Pessoal e Encargos Sociais,Múltiplo,RECOLHIMENTO DE IRRF DARF NUMERADO FOLHA DE PE...,"12,264,146.83"
10657,fev2026,2026-01-02,CAIXA ECONOMICA FEDERAL,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,"PAGAMENTO FOLHA DE PESSOAL ATIVO, INATIVO REF....","11,336,941.93"
2884,jan2026,2025-12-01,CAIXA ECONOMICA FEDERAL,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,"PAGAMENTO FOLHA DE PESSOAL ATIVO, INATIVO REF....","9,292,540.23"
7868,fev2026,2026-01-15,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",Pessoal e Encargos Sociais,Obrigações Patronais,"RECOLHIMENTO DE PSSS FOLHA DE PESSOAL ATIVO, R...","6,760,221.58"
17245,mai2026,2026-04-16,Não informado,Pessoal e Encargos Sociais,Obrigações Patronais,"RECOLHIMENTO DE PSSS FOLHA DE PESSOAL ATIVO, R...","6,753,566.06"
14861,mai2026,2026-04-01,CAIXA ECONOMICA FEDERAL,Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,"PAGAMENTO FOLHA DE PESSOAL ATIVO, INATIVO REF....","6,718,309.80"
1885,jan2026,2025-12-15,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",Pessoal e Encargos Sociais,Obrigações Patronais,"RECOLHIMENTO DE PSSS FOLHA DE PESSOAL ATIVO, R...","6,666,035.42"
14428,abr2026,2026-03-02,CAIXA ECONOMICA FEDERAL,Múltiplo,Múltiplo,"PAGAMENTO FOLHA DE PESSOAL ATIVO, INATIVO REF....","6,665,815.45"
13789,abr2026,2026-03-13,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",Pessoal e Encargos Sociais,Obrigações Patronais,"RECOLHIMENTO DE PSSS FOLHA DE PESSOAL ATIVO, R...","6,637,671.94"
1884,jan2026,2025-12-15,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",Pessoal e Encargos Sociais,Obrigações Patronais,"RECOLHIMENTO DE PSSS FOLHA DE PESSOAL ATIVO, R...","6,630,370.38"
13791,abr2026,2026-03-19,"INST.FED.DE EDUC.,CIENC.E TEC.DO PIAUI",Pessoal e Encargos Sociais,Vencimentos e Vantagens Fixas - Pessoal Civil,RECOLHIMENTO DE IRRF DARF NUMERADO FOLHA DE PE...,"6,470,611.47"

In [122]:
from pathlib import Path

pasta_saida = Path("dados_tratados")
pasta_saida.mkdir(exist_ok=True)

df_tratado.to_csv(
    pasta_saida / "pagamentos_ifpi_tratado_completo.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

df_positivos.to_csv(
    pasta_saida / "pagamentos_ifpi_positivos.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

df_negativos.to_csv(
    pasta_saida / "pagamentos_ifpi_ajustes_negativos.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

resumo_mes.to_csv(
    pasta_saida / "resumo_por_mes.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

resumo_grupo.to_csv(
    pasta_saida / "resumo_por_grupo_despesa.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

resumo_elemento.to_csv(
    pasta_saida / "resumo_por_elemento_despesa.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

resumo_elemento_top15.to_csv(
    pasta_saida / "top15_elementos_despesa.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

resumo_mes_grupo.to_csv(
    pasta_saida / "resumo_mes_grupo.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

pivot_mes_grupo.to_csv(
    pasta_saida / "pivot_mes_grupo.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

top_favorecidos.to_csv(
    pasta_saida / "top_favorecidos.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

maiores_pagamentos.to_csv(
    pasta_saida / "maiores_pagamentos.csv",
    index=False,
    sep=";",
    decimal=",",
    encoding="utf-8-sig"
)

print("Arquivos exportados com sucesso!")

Arquivos exportados com sucesso!